/*
* generated by Xtext
*/
package org.xtext.passi;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DocGenUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.passi.ui.internal.DocGenActivator.getInstance().getInjector("org.xtext.passi.DocGen");
	}
	
}
