/*
 * generated by Xtext
 */
package org.xtext.passi.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DocGenUiModule extends org.xtext.passi.ui.AbstractDocGenUiModule {
	public DocGenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
