/*
 * generated by Xtext
 */
package org.xtext.passi.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.passi.ui.internal.TemplateLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TemplateLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TemplateLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TemplateLanguageActivator.getInstance().getInjector(TemplateLanguageActivator.ORG_XTEXT_PASSI_TEMPLATELANGUAGE);
	}
	
}
