/*
 * generated by Xtext
 */
package org.xtext.passi.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TemplateLanguageUiModule extends org.xtext.passi.ui.AbstractTemplateLanguageUiModule {
	public TemplateLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
