/*
 * generated by Xtext
 */
package org.xtext.passi.ui.contentassist

import org.xtext.passi.ui.contentassist.AbstractDocGenProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class DocGenProposalProvider extends AbstractDocGenProposalProvider {
}
