/*
* generated by Xtext
*/
package org.xtext.passi;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DocGenStandaloneSetup extends DocGenStandaloneSetupGenerated{

	public static void doSetup() {
		new DocGenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

