/**
 * generated by Xtext
 */
package org.xtext.passi.validation;

import org.xtext.passi.validation.AbstractDocGenValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DocGenValidator extends AbstractDocGenValidator {
}
