/*
* generated by Xtext
*/
package org.xtext.passi;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TemplateLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.passi.ui.internal.TemplateLanguageActivator.getInstance().getInjector("org.xtext.passi.TemplateLanguage");
	}
	
}
