/*
* generated by Xtext
*/
package org.xtext.passi.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.passi.services.DocGenGrammarAccess;

public class DocGenParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DocGenGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.passi.parser.antlr.internal.InternalDocGenParser createParser(XtextTokenStream stream) {
		return new org.xtext.passi.parser.antlr.internal.InternalDocGenParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DocGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DocGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
