/*
 * generated by Xtext
 */
package org.xtext.passi;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TemplateLanguageRuntimeModule extends org.xtext.passi.AbstractTemplateLanguageRuntimeModule {

}
