/*
* generated by Xtext
*/
package org.xtext.passi;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TemplateLanguageStandaloneSetup extends TemplateLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new TemplateLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

